### PR TITLE
add extract.arrow_data

### PR DESCRIPTION
**Pull request by j042**
# Overview
adds arrow_data extraction that respects show_options. There are times, where you want to just get data_origin, and arrow_end

## Addressed issues
*  Want arrows only, please

## Showcase
A short / one-liner example to highlight the (new) feature
```python
spline.spline_data["me"] = spp.SplineDataAdapter(spline, locations=np.random.random((10,10)))

edges = spline.extract.arrow_data("me")

begin_and_ends = edges.vertices[edges.edges]
print(begin_and_ends.shape)
# should be (n_locations, 2, dim)
```

## Checklists
* [x] Documentations are up-to-date.
* [ ] Added example(s)
* [x] Added test(s)

### CODE REVIEW

**Review by jzwar — CHANGES_REQUESTED** [review]
I think there might be something wrong here:
```python
import numpy as np
import splinepy as app

circle = spp.helpme.create.surface_circle(1)
circle.spline_data["me"] = circle
circle.show_options["arrow_data"] = "me"
arrow_data = circle.extract.arrow_data("me")
positions = arrow_data.vertices[arrow_data.edges[:, 0]]
directions = positions - arrow_data.vertices[arrow_data.edges[:, 1]]
assert np.allclose(positions, directions)
```
Fails, am I doing it wrong? @j042

**Comment by j042** [comment]
just for your convenience, I will write the scale=1 here
```python
import numpy as np
import splinepy as spp

circle = spp.helpme.create.surface_circle(1)
circle.spline_data["me"] = circle
circle.show_options["arrow_data"] = "me"
circle.show_options["arrow_data_scale"] = 1

arrow_data = circle.extract.arrow_data("me")
positions = arrow_data.vertices[arrow_data.edges[:, 0]]

# directions would be the following
# note, these are "auto" scaled
directions = arrow_data.vertices[arrow_data.edges[:, 1]] - positions

# this should hold
assert np.allclose(directions, circle.sample([100, 100]))
# and this
assert np.allclose(positions, circle.sample([100, 100]))
# and this
assert np.allclose(directions, positions)
```

**Comment by jzwar** [comment]
> ```python
> arrow_data_scale
> ```

Thank you for the clarification!

**Review by jzwar — APPROVED** [review]
LGTM, thanks for the quick help

**Pull request merged**
