### PR TITLE
add SplineList

### PR DESCRIPTION
**Pull request by j042**
# Overview
List like wrapping of cpp vector of splines. Almost last step of preparations for PyMultiPatch 

## Addressed issues
*  easy access of many splines from cpp side

## Checklists
* [ ] Documentations are up-to-date.
* [ ] Added example(s)
* [x] Added test(s)

### CODE REVIEW

**Comment by jzwar** [comment]
Is this relying on stl binding in pybind? Because I don't see an implementation of append :thinking: Also: We should maybe add a python class to perform checks to make it save to use

**Comment by j042** [comment]
[?](https://github.com/pybind/pybind11/blob/ed466da571fbc1d711351eb818e4bf82adb99eca/include/pybind11/stl_bind.h#L145)

**Comment by j042** [comment]
that's unnecessary

**Comment by jzwar** [comment]
> [?](https://github.com/pybind/pybind11/blob/ed466da571fbc1d711351eb818e4bf82adb99eca/include/pybind11/stl_bind.h#L145)

Yes, that was the question

**Comment by j042** [comment]
> > [?](https://github.com/pybind/pybind11/blob/ed466da571fbc1d711351eb818e4bf82adb99eca/include/pybind11/stl_bind.h#L145)
> 
> Yes, that was the question

can't you click the question mark?

**Comment by jzwar** [comment]
> > > [?](https://github.com/pybind/pybind11/blob/ed466da571fbc1d711351eb818e4bf82adb99eca/include/pybind11/stl_bind.h#L145)
> > 
> > 
> > Yes, that was the question
> 
> can't you click the question mark?

I mean : Yes, that was the question, thank you for answering! <3

**Review by jzwar — APPROVED** [review]
Nice, is perfect for making multi-patch sampling much more efficient.

**Pull request merged**
