### PR TITLE
data_name -> data

### PR DESCRIPTION
**Pull request by j042**
# Overview
follow up of tataratat/gustaf#188

## Addressed issues
*  `data` is clear enough

## Showcase
A short / one-liner example to highlight the (new) feature
```python
import splinepy

spline.spline_data["this"] = this_array
spline.show() # shows "this" right away

spline.spline_data["dis"] = dis_array
spline.show_options["data"] = "dis"
spline.show() # shows "dis"
```

## Checklists
* [ ] Documentations are up-to-date.
* [ ] Added example(s)
* [ ] Added test(s)

### CODE REVIEW

**Review by clemens-fricke — APPROVED** [review]
LGTM, only `FFD` example is failing. But I think this is due to another previous PR?

**Review by jzwar — APPROVED** [review]
LGTM

**Comment by j042** [comment]
@jzwar suggested that we use `field` instead of `data`

**Comment by j042** [comment]
open for discussion for the future

**Pull request merged**
