### PR TITLE
Enforce Recomputation of Multipatch Interfaces

### PR DESCRIPTION
**Pull request by jzwar**
# Overview
As the title says.

## Checklists
* [x] Documentations are up-to-date.
* [ ] Added example(s)
* [ ] Added test(s)

### CODE REVIEW

**Comment by j042** [comment]
When was this causing err?

**Comment by jzwar** [comment]
> When was this causing err?

No error, but also no way to recompute once done. This just adds a new option.

**Comment by j042** [comment]
> > When was this causing err?
> 
> No error, but also no way to recompute once done. This just adds a new option.

I think I've mentioned this back then: what about removing property/setter and use "vedo style":
```
mp.interface(new_inter)  # setter
interf = mp.interface()  # getter
```

**Comment by jzwar** [comment]
> > > When was this causing err?
> > 
> > 
> > No error, but also no way to recompute once done. This just adds a new option.
> 
> I think I've mentioned this back then: what about removing property/setter and use "vedo style":
> 
> ```python
> mp.interface(new_inter)  # setter
> interf = mp.interface()  # getter
> recomp_interf = mp.interface(recompute=False) # getter
> ```

Naaaaa, I like the properties. In 99% of cases, you need no recomputation

**Comment by j042** [comment]
> > > > When was this causing err?
> > > 
> > > 
> > > No error, but also no way to recompute once done. This just adds a new option.
> > 
> > 
> > I think I've mentioned this back then: what about removing property/setter and use "vedo style":
> > ```python
> > mp.interface(new_inter)  # setter
> > interf = mp.interface()  # getter
> > recomp_interf = mp.interface(recompute=False) # getter
> > ```
> 
> Naaaaa, I like the properties. In 99% of cases, you need no recomputation

1% is what matters

**Comment by jzwar** [comment]
> > > > > When was this causing err?
> > > > 
> > > > 
> > > > No error, but also no way to recompute once done. This just adds a new option.
> > > 
> > > 
> > > I think I've mentioned this back then: what about removing property/setter and use "vedo style":
> > > ```python
> > > mp.interface(new_inter)  # setter
> > > interf = mp.interface()  # getter
> > > recomp_interf = mp.interface(recompute=False) # getter
> > > ```
> > 
> > 
> > Naaaaa, I like the properties. In 99% of cases, you need no recomputation
> 
> 1% is what matters

Let's not get political 😄 I like the properties

**Review by j042 — CHANGES_REQUESTED** [review]
Can we go with setter and getter for cpp? I don't like that you have to give empty list to give a recompute flag (`interfaces = super().interfaces([], recompute)`)
```cpp
PyMultipatch::SetInterface(py::array_t<double>);

PyMultipatch::GetInterface(bool recompute);
```

**Comment by jzwar** [comment]
> Can we go with setter and getter for cpp? I don't like that you have to give empty list to give a recompute flag (`interfaces = super().interfaces([], recompute)`)
> 
> ```c++
> PyMultipatch::SetInterface(py::array_t<double>);
> 
> PyMultipatch::GetInterface(bool recompute);
> ```

done

**Review by j042 — APPROVED** [review]
Great and Clear, thank you!

**Pull request merged**
