### PR TITLE
use RemoveOneParametricDimension() for slicing

### PR DESCRIPTION
**Pull request by j042**
# Overview
Creating boundary spline can be expensive for BSpline Families, as it will recreate the basis functions. This PR avoids it by just taking pointers to existing data structures (they are already shared_ptrs) for boundary spline. Much cheaper. Will possibly use boundaries to plot in gustaf rather than organized queries.

## Addressed issues
*  Maybe expensive to extract boundaries.

## Checklists
* [ ] Documentations are up-to-date.
* [ ] Added example(s)
* [ ] Added test(s)

### CODE REVIEW

**Review by jzwar — APPROVED** [review]
Looks good, I checked out the SplineLib changes, besides the usual `int` vs `size_t` debate, it checks out. Thanks for the work. 
Is this frequently used or why is there a need to adapt this?

**Comment by jzwar** [comment]
> Looks good, I checked out the SplineLib changes, besides the usual `int` vs `size_t` debate, it checks out. Thanks for the work. Is this frequently used or why is there a need to adapt this?

Is there a test for sub-dim extraction besides boundary extraction? If not, would be nice to add one.

**Comment by j042** [comment]
1) Or you mean `int` vs `NamedType`? for plotting.
2) no, but there's no sub-dim extraction besides boundary extraction

**Comment by jzwar** [comment]
Can be merged

**Pull request merged**
