### PR TITLE
Bugfix - Wrong indices for back substitution

### PR DESCRIPTION
**Pull request by jzwar**
The indices of the solution vector do not change as the pivoting only affects the rows of the matrix and the lhs, but not the solution (columns remain unchanged).

@j042, please verify

## Addressed issues
*  #385 

## Checklists
* [x] Documentations are up-to-date.
* [ ] Added example(s)
* [ ] Added test(s)

### CODE REVIEW

**Comment by jzwar** [comment]
Also :
I would like to delete the unused function: `GaussWithPivot` to avoid confusion

**Comment by j042** [comment]
What a good catch, thanks! I agree with some clean up. Maybe we can add LAPACK based solve for debug or maybe use that as numpy always comes with lapack/blas

**Comment by jzwar** [comment]
> What a good catch, thanks! I agree with some clean up. Maybe we can add LAPACK based solve for debug or maybe use that as numpy always comes with lapack/blas

@j042 If it is ok with you, I would just write an issue to push this to later. Imo, we can already merge this pr and wait with both clean up and bugfix for convergence issues for later...

**Comment by j042** [comment]
Sure

**Review by j042 — APPROVED** [review]
Thanks!

**Pull request merged**
